version: "3.9"

volumes:
  processedvol:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/MEDIA/processed
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"
  downloadsvol:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/MEDIA/downloads
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"
  musicvollibrary:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/MUSIC/library
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"
  musicvolincoming:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/MUSIC/incoming
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"

networks:
  default:
    driver: bridge
  nginx_proxy_manager_proxy:
    name: nginx_proxy_manager_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.89.0/24


x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

x-common-keys-media-services: &common-keys-media-services
  networks:
    - nginx_proxy_manager_proxy
  security_opt:
    - no-new-privileges:true
  restart: always
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 400M
  labels:
    logging: "promtail"
    logging_jobname: "containerlogs"

services:
  qbittorrent:    
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/qbittorrent:5.1.2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 800M
    #network_mode: container:transmission-vpn # Passing network through Transmission Container if VPN is needed.
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - $DOCKERDIR/appdata/qbittorrent:/config
      - downloadsvol:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: 002

  transmission:
    profiles:
      - disabled
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/transmission:4.0.6
    ports:
      - "9091:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/transmission-vpn/data:/data
      - $DOCKERDIR/appdata/transmission-vpn/config:/config
      - downloadsvol:/data/downloads
    environment:
      <<: *default-tz-puid-pgid
      LOCAL_NETWORK: "$LOCAL_NETWORK"
      UMASK_SET: 2
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_RPC_HOST_WHITELIST: "127.0.0.1,$SERVER_IP"
      TRANSMISSION_RPC_PASSWORD: $TRANSMISSION_RPC_PASSWORD
      TRANSMISSION_RPC_USERNAME: $TRANSMISSION_RPC_USERNAME
      TRANSMISSION_UMASK: 002
      TRANSMISSION_RATIO_LIMIT: 1.00
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_DOWN: 40000
      TRANSMISSION_ALT_SPEED_ENABLED: "false"
      TRANSMISSION_ALT_SPEED_UP: 250
      TRANSMISSION_SPEED_LIMIT_DOWN: 80000
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "false"
      TRANSMISSION_SPEED_LIMIT_UP: 500
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "false"
      TRANSMISSION_INCOMPLETE_DIR: /data/downloads/torrents/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      TRANSMISSION_WATCH_DIR: /data/downloads/torrents
      TRANSMISSION_WATCH_DIR_ENABLED: "false"
      TRANSMISSION_DOWNLOAD_DIR: /data/downloads/complete
      LOG_TO_STDOUT: "true"
  
  prowlarr:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: linuxserver/prowlarr:1.37.0
    networks:
      nginx_proxy_manager_proxy:
        ipv4_address: 192.168.89.162
    ports:
      - "9696:9696"
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  radarr:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: linuxserver/radarr:5.26.2 # latest was causing "Error parsing column 45"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
    networks:
      nginx_proxy_manager_proxy:
        ipv4_address: 192.168.89.164
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - downloadsvol:/data/downloads
      - processedvol:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  sonarr:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: linuxserver/sonarr:4.0.15
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
    networks:
      nginx_proxy_manager_proxy:
        ipv4_address: 192.168.89.167
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - downloadsvol:/data/downloads
      - processedvol:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
 
  plexms:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image:  plexinc/pms-docker:1.41.9.9961-46083195d
    deploy: 
      resources:
        limits:
          cpus: '4'
          memory: 2500M
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      # - "1900:1900/udp" # Conflicts with xTeVe and Synology default ports
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      # - "33400:33400" # If you use Plex Web Tools
    #devices:
    #  - /dev/dri:/dev/dri # for harware transcoding
    volumes:
      - $DOCKERDIR/appdata/plexms:/config
      - processedvol:/media
      - musicvollibrary:/music
      - /dev/shm:/transcode
    environment:
      TZ: $TZ
      HOSTNAME: "plex.home"
      PLEX_CLAIM_FILE: $PLEX_CLAIM
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: http://192.168.20.65:32400/

  overseerr:
    image: linuxserver/overseerr:1.34.0
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 800M
    environment:
       <<: *default-tz-puid-pgid
    ports:
      - 5055:5055
    volumes:
      - $DOCKERDIR/appdata/overseerr:/config

  headphones:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    profiles:
      - disabled
    image: lscr.io/linuxserver/headphones:latest
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/appdata/headphones:/config
      - downloadsvol:/data/downloads
      - musicvollibrary:/music
      - musicvolincoming:/incoming
    ports:
      - 1111:8181
