version: "3.9"

########################### NETWORKS
# You may customize the network subnet (192.168.89.0/24) below as you please.
# Docker Compose version 3.5 or higher required to define networks this way.

volumes:
  processedvol:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/MEDIA/processed
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"
  downloadsvol:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/MEDIA/downloads
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"
  musicvollibrary:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/MUSIC/library
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"
  musicvolincoming:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/MUSIC/incoming
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"

networks:
  default:
    driver: bridge
  nginx_proxy_manager_proxy:
    name: nginx_proxy_manager_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.89.0/24
  # If you decide to use Socket Proxy, you need socket_proxy network as we. See https://www.smarthomebeginner.com/traefik-docker-security-best-practices/#9_Use_a_Docker_Socket_Proxy

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the dependent services/apps
x-common-keys-media-services: &common-keys-media-services
  networks:
    - nginx_proxy_manager_proxy
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 200M
  labels:
    logging: "promtail"
    logging_jobname: "containerlogs"

########################### SERVICES
services:
  # heimdall:
  #   <<: *common-keys-media-services # See EXTENSION FIELDS at the top
  #   image: lscr.io/linuxserver/heimdall
  #   container_name: heimdall
  #   ports:
  #     - "83:80" # 80 to 82 already taken by other services
  #     # - "444:443" # 443 used by Nginx Proxy Manager. Disabled because we will put Heimdall behind proxy.
  #   volumes:
  #     - $DOCKERDIR/appdata/heimdall:/config
  #   environment:
  #     <<: *default-tz-puid-pgid

  ############################# DOWNLOADERS
  qbittorrent:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M
    #network_mode: container:transmission-vpn # Passing network through Transmission Container if VPN is needed.
    ports:
      - "8080:8080"
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - $DOCKERDIR/appdata/qbittorrent:/config
      - downloadsvol:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
    environment:
      <<: *default-tz-puid-pgid
      UMASK_SET: 002

  transmission:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    ports:
      - "9091:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/transmission-vpn/data:/data
      - $DOCKERDIR/appdata/transmission-vpn/config:/config
      - downloadsvol:/data/downloads
    environment:
      <<: *default-tz-puid-pgid
      LOCAL_NETWORK: "$LOCAL_NETWORK"
      UMASK_SET: 2
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_RPC_HOST_WHITELIST: "127.0.0.1,$SERVER_IP"
      TRANSMISSION_RPC_PASSWORD: $TRANSMISSION_RPC_PASSWORD
      TRANSMISSION_RPC_USERNAME: $TRANSMISSION_RPC_USERNAME
      TRANSMISSION_UMASK: 002
      TRANSMISSION_RATIO_LIMIT: 1.00
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_DOWN: 40000
      TRANSMISSION_ALT_SPEED_ENABLED: "false"
      TRANSMISSION_ALT_SPEED_UP: 250
      TRANSMISSION_SPEED_LIMIT_DOWN: 80000
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "false"
      TRANSMISSION_SPEED_LIMIT_UP: 500
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "false"
      TRANSMISSION_INCOMPLETE_DIR: /data/downloads/torrents/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      TRANSMISSION_WATCH_DIR: /data/downloads/torrents
      TRANSMISSION_WATCH_DIR_ENABLED: "false"
      TRANSMISSION_DOWNLOAD_DIR: /data/downloads/complete
      LOG_TO_STDOUT: "true"
  ############################# PVRS

  # Prowlarr - Indexer Proxy
  prowlarr:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    networks:
      nginx_proxy_manager_proxy:
        ipv4_address: 192.168.89.162
    ports:
      - "9696:9696"
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  # jackett:
  #   <<: *common-keys-media-services # See EXTENSION FIELDS at the top
  #   image: lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   environment:
  #     <<: *default-tz-puid-pgid
  #   volumes:
  #     - $DOCKERDIR/appdata/jackett:/config
  #     - downloadsvol:/downloads
  #   ports:
  #     - 9117:9117

  # Radarr - Movie management
  radarr:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/radarr:4.7.5 # latest was causing "Error parsing column 45"
    container_name: radarr
    networks:
      nginx_proxy_manager_proxy:
        ipv4_address: 192.168.89.164
    ports:
      - "7878:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - downloadsvol:/data/downloads
      - processedvol:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  # Sonarr - TV Shows management
  sonarr:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/sonarr:3.0.10
    container_name: sonarr
    networks:
      nginx_proxy_manager_proxy:
        ipv4_address: 192.168.89.167
    ports:
      - "8989:8989"
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - downloadsvol:/data/downloads
      - processedvol:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  # # Readarr - Books management
  # readarr:
  #   <<: *common-keys-media-services # See EXTENSION FIELDS at the top
  #   image: hotio/readarr:nightly
  #   container_name: readarr
  #   ports:
  #     - "8987:8987"
  #   volumes:
  #     - $DOCKERDIR/appdata/readarr:/config
  #     - processedvol:/data
  #     - "/etc/localtime:/etc/localtime:ro"
  #   environment:
  #     <<: *default-tz-puid-pgid
  #     UMASK: 002
  #     #ARGS: ""

  ############################# MEDIA
  # Plex - Media Server
  plexms:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    #image: plexinc/pms-docker:public
    image:  plexinc/pms-docker:1.32.5.7516-8f4248874
    container_name: plexms
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2000M
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      # - "1900:1900/udp" # Conflicts with xTeVe and Synology default ports
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      # - "33400:33400" # If you use Plex Web Tools
    #devices:
    #  - /dev/dri:/dev/dri # for harware transcoding
    volumes:
      - $DOCKERDIR/appdata/plexms:/config
      - processedvol:/media
      - musicvollibrary:/music
      - /dev/shm:/transcode
    environment:
      TZ: $TZ
      HOSTNAME: "plex.home"
      PLEX_CLAIM_FILE: $PLEX_CLAIM
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: http://192.168.20.65:32400/

  # Tautulli - Plex Stats and Monitoring
  # tautulli:
  #   <<: *common-keys-media-services # See EXTENSION FIELDS at the top
  #   image: linuxserver/tautulli:latest
  #   container_name: tautulli
  #   ports:
  #     - "8181:8181"
  #   volumes:
  #     - $DOCKERDIR/appdata/tautulli/config:/config
  #     - $DOCKERDIR/appdata/plexms/Library/Application Support/Plex Media Server/Logs:/logs:ro # For tautulli Plex log viewer
  #   environment:
  #     <<: *default-tz-puid-pgid

  # Ombi - Media Requests
  overseerr:
    image: linuxserver/overseerr:1.33.2
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    container_name: overseerr
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    environment:
       <<: *default-tz-puid-pgid
    ports:
      - 5055:5055
    volumes:
      - $DOCKERDIR/appdata/overseerr:/config
  # ombi:
  #   <<: *common-keys-media-services # See EXTENSION FIELDS at the top
  #   image: linuxserver/ombi:latest
  #   container_name: ombi
  #   ports:
  #     - "3579:3579"
  #   volumes:
  #     - $DOCKERDIR/appdata/ombi:/config
  #   environment:
  #     <<: *default-tz-puid-pgid

  # navidrome:
  #   <<: *common-keys-media-services # See EXTENSION FIELDS at the top
  #   image: deluan/navidrome:latest
  #   ports:
  #     - "4533:4533"
  #   environment:
  #     # Optional: put your config options customization here. Examples:
  #     ND_SCANSCHEDULE: 1h
  #     ND_LOGLEVEL: info  
  #     ND_SESSIONTIMEOUT: 24h
  #     ND_BASEURL: ""
  #   volumes:
  #     - "$DOCKERDIR/appdata/navidrome:/data"
  #     - "musicvollibrary:/music:ro"

  headphones:
    <<: *common-keys-media-services # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/headphones:latest
    container_name: headphones
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/appdata/headphones:/config
      - downloadsvol:/data/downloads
      - musicvollibrary:/music
      - musicvolincoming:/incoming
    ports:
      - 1111:8181
