version: "3.9"

volumes:
  datavol:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/BACKUP/nextcloud
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"
  
services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 500M
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  app:
    image: nextcloud:27
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 800M
    ports:
      - "9999:80"
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ./nextcloud/html:/var/www/html
      - datavol:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
  # db:
  #   image: mariadb:10.1
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: 500M
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #   volumes:
  #     - ./filerun/db:/var/lib/mysql

  # web:
  #   image: filerun/filerun:7.4
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: 500M
  #   environment:
  #     FR_DB_HOST: db
  #     FR_DB_PORT: 3306
  #     FR_DB_NAME: ${MYSQL_DATABASE}
  #     FR_DB_USER: ${MYSQL_USER}
  #     FR_DB_PASS: ${MYSQL_PASSWORD}
  #     APACHE_RUN_USER: www-data
  #     APACHE_RUN_USER_ID: 33
  #     APACHE_RUN_GROUP: www-data
  #     APACHE_RUN_GROUP_ID: 33
  #   depends_on:
  #     - db
  #   links:
  #     - db:db
  #   ports:
  #     - "9999:80"
  #   volumes:
  #     - ./filerun/html:/var/www/html
  #     - filerunvol:/user-files