version: "3.9"

volumes:
  datavol:
    driver: local
    driver_opts:
      type: cifs
      device: //nas.home/BACKUP/nextcloud
      o: "addr=nas.home,username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0,uid=${PUID},gid=${PGID}"
  
services:
  db:
    image: mariadb:10.6.22
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1000M
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  app:
    image: nextcloud:31
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1500M
    ports:
      - "9999:80"
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ./nextcloud/html:/var/www/html
      - datavol:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db